names:
- DouyinEarningTasksPageInfo
- DouyinOpenChestRewardsPageInfo
- DouyinTotalRewardsPageInfo
- DouyinNextAdPageInfo
- DouyinAdShowPageInfo
- DouyinHomePageInfo
- AndroidDesktopPageInfo
- OtherPageInfo
nc: 8
path: D:\ldd\AI\app\auto_click_ad_douyin_yolo_train\datasets\classification
train: train
val: val
