names:
- ho_earning_tasks_button
- ho_earning_tasks_assistive_button
- ta_daily_coins_box
- ta_total_coins_box
- ta_watch_video_button
- ta_watch_ad_button
- ta_turn_card_button
- ta_open_the_chest_button
- ta_sroll_bottom_box
- ta_sroll_top_box
- ad_remaining_time_button
- ad_remaining_time_and_xxx_coins_button
- ad_remaining_time_and_xxx_coins_box
- ad_close_button
- ad_open_app_and_experience_button
- ad_open_app_button
- po_back_button
- po_ad_coins_box
- po_watch_ad_get_xxx_coins_button
- po_watch_ad_button
- po_exit_button
- po_happy_to_receive_button
- po_close_button
- de_douyin_lite_app_icon
- de_kuaishou_lite_app_icon
- de_hongguo_app_icon
- de_jinritoutiao_lite_app_icon
- de_wukongliulanqi_app_icon
- de_baidu_lite_app_icon
- de_close_app_button
nc: 30
path: D:\ldd\AI\app\auto_click_ad_douyin_yolo_train_newcls_kuaishou\datasets\detection
train: images/train
val: images/val
